### PR TITLE
enhance code format; fix #95

### LINKED ISSUE #95: Set listener while building a dialog
In some situation, we will define a `Listener` neither in a `Activity` or in a `Fragment`.

For more convenient usage, we should allow set the `Listener` while build the dialog. For example:

```
ListDialogFragment
    .createBuilder(c, getSupportFragmentManager())
    .setTitle("Your favorite character:")
    .setItems(new String[]{"Jayne", "Malcolm", "Kaylee",
        "Wash", "Zoe", "River"})
    .setRequestCode(REQUEST_LIST)
     //  set a Listener
    .setListDialogListener(new IListDialogListener() {
        @Override
        public void onListItemSelected(String value, int number, int requestCode) {
            
        }

        @Override
        public void onCancelled(int requestCode) {

        }
    })
    .show();

}
```

### PR DESCRIPTION
**Pull request by liaohuqiu**

### CODE REVIEW

**Comment by tomik-dev** [comment]
Hi, thank you for your effort.
But your proposed changes cannot be merged because they go directly against the current architecture of styled dialogs. We don't want to support setting dialog listeners in builders since it's a very error-prone feature breaking correct handling of device rotation and causing memory leaks. There are also no plans to add such feature in future releases.
The only safe approach for handling listeners is via target fragment and activity listeners.

**Comment by liaohuqiu** [comment]
Memory leaks? So, what do you think about `View.setOnClickListener()` ?

**Comment by liaohuqiu** [comment]
If I hava a Customized View used in multiple Activity, and I want to show a dialog to show some information related to this `Customized View`, do you mean that I should process the listener in every Activyt?

**Comment by tomik-dev** [comment]
View listeners are different. Your general listener is strongly referenced in the `DialogFragment` when you pass an inner class of an `Activity` you risk leaking the activity when you rotate the device.
To solve your problem can have a common ancestor of your activities or if that's really not the case you can always fork styled dialogs and do it your way (I guess there might already be some forks like that).

**Comment by liaohuqiu** [comment]
OK. Thank you for your nice explanation and your patient.

**Pull request closed without merging**
