### PR TITLE
Dark Theme for dialog box.

### PR DESCRIPTION
**Pull request by AnuraxSharma1512**
New Dark Theme.

Demo activity is changed in order to switch from dark theme to light theme.

screenshot_2015-02-09-00-01-42
screenshot_2015-02-09-00-01-53
screenshot_2015-02-09-00-02-01

### CODE REVIEW

**Comment by destil** [comment]
Hi, 
I see that you updated the code. Please add a comment when you do, I receive notifications only about comments.

The code looks much better now. 
Issues:
- it still not formatted to our coding style. I noticed that the ifs don't have required number of spaces and sometimes there are no {} brackets
- I don't see the `useDarkTheme()` method in the builder we discussed
- Why are you changing `ListDialogFragment`? I feel that it might be done in cleaner way.

**Comment by AnuraxSharma1512** [comment]
I have formatted the code.

Implemented the useDarkTheme method.

And simplified the listDialogFragment class to some extend.

**Comment by destil** [comment]
Almost there :)

It looks like you didn't use our [code formatting configuration](https://github.com/avast/android-styled-dialogs/blob/master/code-formatting-config.xml). Can you reformat with our configuration?

**Comment by AnuraxSharma1512** [comment]
I have reformatted the code.

**Comment by destil** [comment]
It looks like we had some files with bad formatting ourselves :) Thanks for fixing that. Good job and thanks for your contribution!

**Comment by AnuraxSharma1512** [comment]
Its always honour to works for open source project and in return receiving thanks..

Looking forward to work more.

**Pull request merged**
